openapi: 3.0.1
info:
  title: create-monday-items-by-column-title
  description: An API for StudioBand GravityForm webhooks
  version: 1.0.0
tags:
  - name: Entries
    description: Entries created by GravityForms
  - name: Specification
    description: The swagger API specification
  - name: System
    description: Status status
paths:
  /api/entry:
    post:
      tags:
        - Entries
      description: Create an entry submitted from GravityForms
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mondayBoardId:
                  type: string
                  example: "123456789"
                mondayDeveloperToken:
                  type: string
                  example: "TOKEN"
                name:
                  type: string
                  example: "John Smith"
                mondayNameColumn:
                  type: string
                  example: "Full Name"
                business:
                  type: string
                  example: "CompanyCo"
                mondayBusinessColumn:
                  type: string
                  example: "Company"
                email:
                  type: string
                  example: "john@companyco.com"
                mondayEmailColumn:
                  type: string
                  example: "Email"
                contactNumber:
                  type: string
                  example: "0412 123 456"
                mondayContactNumberColumn:
                  type: string
                  example: "Phone"
                message:
                  type: string
                  example: "Hello there!"

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ok
        401:
          description: Unauthorised
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: unrecognised Authorization token
  /health:
    get:
      tags:
        - System
      responses:
        200:
          description: Healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ok

  /api/spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-CREATE-MONDAY-ITEMS-API-KEY
